#!/usr/bin/env bash
# https://git-scm.com/docs/githooks#_pre_commit
set -eo pipefail

currentBranch="$(git rev-parse --abbrev-ref HEAD)"
branchNamePattern="^(ISSUE-\d+(-[^\W_]+)*|TECH(-[^\W_]+)+|HEAD)$"

if ! echo "$currentBranch" | grep "$branchNamePattern" -qE; then
  echo >&2 "ERROR: pre-commit git hook failed."
  echo >&2 "Branch name must contain issue id and match the pattern: \"ISSUE-1234{-additional-description}\"."
  echo >&2 "Your branch name:"
  echo >&2 "$currentBranch"
  exit 1
fi
