check_android_30_task:
  name: Run Android instrumented tests on API 30
  env:
    DISPLAY: :99
  only_if: $CIRRUS_PR != '' && $CIRRUS_BASE_BRANCH == 'master'
  skip: "changesIncludeOnly('NOTICE.txt', 'LICENSE.txt', '**.{md,html}')"

  container:
    image: cirrusci/android-sdk:33
    kvm: true
    cpu: 8
    memory: 24G
  start_adb_server_background_script:
    java -jar artifacts/adbserver-desktop.jar || true
  accept_licenses_script:
    echo yes | sdkmanager --licenses
  install_emulator_script:
    # x86_64 somehow affect the "call" test
    sdkmanager --install "system-images;android-30;google_apis;x86"
  create_avd_script: |
    echo no | avdmanager create avd --force -n emulator -k "system-images;android-30;google_apis;x86"
    echo skin.name=768x1280 >> ~/.android/avd/emulator.avd/config.ini
    echo skin.path=_no_skin >> ~/.android/avd/emulator.avd/config.ini
    echo hw.lcd.density=320 >> ~/.android/avd/emulator.avd/config.ini
    echo hw.lcd.height=1280 >> ~/.android/avd/emulator.avd/config.ini
    echo hw.lcd.width=768 >> ~/.android/avd/emulator.avd/config.ini
  start_avd_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd emulator
    -no-audio
    -no-boot-anim
    -gpu swiftshader_indirect
    -no-snapshot
    -no-window
  assemble_instrumented_tests_script:
    ./gradlew -PCI=true assembleDebugAndroidTest
  wait_for_avd_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  configure_avd_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
    adb shell settings put secure spell_checker_enabled 0
    adb shell settings put secure show_ime_with_hard_keyboard 1
  start_logcat_background_script:
    adb logcat > log.log
  run_tests_script:
    ./gradlew -PCI=true connectedDebugAndroidTest
  always:
    stop_logcat_script: |
      if [[ $(adb devices | awk 'NR>1 {print $1}') =~ "emulator.*" ]]; then
        adb logcat -c
      fi
    pull_artifacts_script:
      adb exec-out sh -c "cd /sdcard && tar cf - Documents" > artifacts.tar
    logs_artifacts:
      path: log.log
    artifacts_artifacts:
      path: "artifacts.tar"
    sample_report_artifacts:
      path: "samples/kaspresso-sample/build/reports/androidTests/connected/**/*"
    kautomator_sample_report_artifacts:
      path: "samples/kautomator-sample/build/reports/androidTests/connected/**/*"
    tutorial_report_artifacts:
      path: "tutorial/build/reports/androidTests/connected/**/*"
    allure_report_artifacts:
      path: "samples/kaspresso-allure-support-sample/build/reports/androidTests/connected/**/*"

check_android_33_task:
  name: Run Android instrumented tests on API 33
  env:
    DISPLAY: :99
  only_if: $CIRRUS_PR != '' && $CIRRUS_BASE_BRANCH == 'master'
  skip: "changesIncludeOnly('NOTICE.txt', 'LICENSE.txt', '**.{md,html}')"

  container:
    image: cirrusci/android-sdk:33
    kvm: true
    cpu: 8
    memory: 24G
  start_adb_server_background_script:
    java -jar artifacts/adbserver-desktop.jar || true
  accept_licenses_script:
    echo yes | sdkmanager --licenses
  install_emulator_script:
    sdkmanager --install "system-images;android-33;google_apis;x86_64"
  create_avd_script: |
    echo no | avdmanager create avd --force -n emulator -k "system-images;android-33;google_apis;x86_64"
    echo 'hw.ramSize=2048MB' >> ~/.android/avd/emulator.avd/config.ini
  start_avd_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd emulator
    -no-audio
    -no-boot-anim
    -gpu swiftshader_indirect
    -no-snapshot
    -no-window
  assemble_instrumented_tests_script:
    ./gradlew -PCI=true assembleDebugAndroidTest
  wait_for_avd_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  configure_avd_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
    adb shell settings put secure spell_checker_enabled 0
    adb shell settings put secure show_ime_with_hard_keyboard 1
    adb shell cmd overlay enable com.android.internal.systemui.navbar.threebutton
  start_logcat_background_script:
    adb logcat > log.log
  run_tests_script:
    ./gradlew -PCI=true connectedDebugAndroidTest
  always:
    stop_logcat_script: |
      if [[ $(adb devices | awk 'NR>1 {print $1}') =~ "emulator.*" ]]; then
        adb logcat -c
      fi
    pull_artifacts_script:
      adb exec-out sh -c "cd /sdcard && tar cf - Documents" > artifacts.tar
    logs_artifacts:
      path: log.log
    artifacts_artifacts:
      path: "artifacts.tar"
    sample_report_artifacts:
      path: "samples/kaspresso-sample/build/reports/androidTests/connected/**/*"
    kautomator_sample_report_artifacts:
      path: "samples/kautomator-sample/build/reports/androidTests/connected/**/*"
    tutorial_report_artifacts:
      path: "tutorial/build/reports/androidTests/connected/**/*"
    allure_report_artifacts:
      path: "samples/kaspresso-allure-support-sample/build/reports/androidTests/connected/**/*"

check_android_21_task:
  name: Run Android instrumented tests on API 21
  env:
    DISPLAY: :99
  only_if: $CIRRUS_PR != '' && $CIRRUS_BASE_BRANCH == 'master'
  skip: "changesIncludeOnly('NOTICE.txt', 'LICENSE.txt', '**.{md,html}')"

  container:
    image: cirrusci/android-sdk:33
    kvm: true
    cpu: 8
    memory: 24G
  start_adb_server_background_script:
    java -jar artifacts/adbserver-desktop.jar || true
  accept_licenses_script:
    echo yes | sdkmanager --licenses
  install_emulator_script: |
    # x86_64 somehow affect the "call" test
    sdkmanager emulator
    sdkmanager --install "system-images;android-21;default;x86"
  create_avd_script:
    echo no | avdmanager create avd --force
    -c 1024M
    -n emulator
    -k "system-images;android-21;default;x86"
  start_avd_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd emulator
    -no-audio
    -no-boot-anim
    -gpu swiftshader_indirect
    -no-snapshot
    -no-window
  assemble_instrumented_tests_script:
    ./gradlew -PCI=true assembleDebugAndroidTest
  wait_for_avd_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  configure_avd_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
    adb shell settings put secure spell_checker_enabled 0
    adb shell settings put secure show_ime_with_hard_keyboard 1
  start_logcat_background_script:
    adb logcat > log.log
  run_tests_script:
    ./gradlew -PCI=true connectedDebugAndroidTest
  always:
    stop_logcat_script: |
      if [[ $(adb devices | awk 'NR>1 {print $1}') =~ "emulator.*" ]]; then
        adb logcat -c
      fi
    pull_artifacts_script:
      adb exec-out sh -c "cd /sdcard && tar cf - Documents" > artifacts.tar
    logs_artifacts:
      path: log.log
    artifacts_artifacts:
      path: "artifacts.tar"
    sample_report_artifacts:
      path: "samples/kaspresso-sample/build/reports/androidTests/connected/**/*"
    kautomator_sample_report_artifacts:
      path: "samples/kautomator-sample/build/reports/androidTests/connected/**/*"
    tutorial_report_artifacts:
      path: "tutorial/build/reports/androidTests/connected/**/*"
    allure_report_artifacts:
      path: "samples/kaspresso-allure-support-sample/build/reports/androidTests/connected/**/*"
