check_android_task:
  name: Run Android instrumented tests
  env:
    DISPLAY: :99
  only_if: $CIRRUS_PR != '' && $CIRRUS_BASE_BRANCH == 'master'

  container:
    image: cirrusci/android-sdk:30
    kvm: true
    cpu: 8
    memory: 24G
  # xfce4 somehow helps to pass "Geolocation" test
  install_de_script: |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install xfce4 -y
    apt-get purge -y pm-utils xscreensaver*
    apt-get install xvfb -y
  start_de_background_script: |
    Xvfb :99 -screen 0 1000x1000x16 &
    sleep 5
    startxfce4
  start_adb_server_background_script:
    java -jar artifacts/adbserver-desktop.jar || true
  accept_licenses_script:
    echo yes | sdkmanager --licenses
  install_emulator_script:
    # x86_64 somehow affect the "call" test
    sdkmanager --install "system-images;android-30;google_apis;x86"
  create_avd_script:
    echo no | avdmanager create avd --force
    -n emulator
    -k "system-images;android-30;google_apis;x86"
  start_avd_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd emulator
    -no-audio
    -no-boot-anim
    -gpu swiftshader_indirect
    -no-snapshot
  # -no-window is not used here because the flag somehow affects the "GPS" test. actual for API=30
  assemble_instrumented_tests_script:
#    ./gradlew assembleDebugAndroidTest
    ./gradlew  :samples:kautomator-sample:assembleDebugAndroidTest
  wait_for_avd_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  configure_avd_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
    adb shell settings put secure spell_checker_enabled 0
    adb shell settings put secure show_ime_with_hard_keyboard 1
  start_logcat_background_script:
    adb logcat > log.log
  run_tests_script:
#    ./gradlew connectedDebugAndroidTest
    ./gradlew :samples:kautomator-sample:installDebugAndroidTest
    adb shell am instrument -w -e class com.kaspersky.kaspresso.kautomatorsample.test.InterceptorTest com.kaspersky.kaspresso.kautomatorsample.test/androidx.test.runner.AndroidJUnitRunner
  always:
    stop_logcat_script:
      adb logcat -c
    pull_artifacts_script:
      adb exec-out sh -c "cd /sdcard && tar cf - Documents" > artifacts.tar
    logs_artifacts:
      path: log.log
    artifacts_artifacts:
      path: "artifacts.tar"
    sample_report_artifacts:
      path: "samples/kaspresso-sample/build/reports/androidTests/connected/**/*"
    kautomator_sample_report_artifacts:
      path: "samples/kautomator-sample/build/reports/androidTests/connected/**/*"
    tutorial_report_artifacts:
      path: "tutorial/build/reports/androidTests/connected/**/*"
    allure_report_artifacts:
      path: "samples/kaspresso-allure-support-sample/build/reports/androidTests/connected/**/*"

