version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Run Code Analysis
          command: ./gradlew detekt
      - run:
          name: Build
          command: ./gradlew assemble
      - store_artifacts:
          path: kaspresso/build/reports
          destination: reports/kaspresso
      - store_artifacts:
          path: uiautomator_dsl/build/reports
          destination: reports/uiautomator_dsl
      - store_test_results: 
          path: kaspresso/build/test-results
  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - run:
          name: Inject environment variables
          command: |
            echo $'\n'bintrayuser=$bintrayuser >> ${HOME}/.gradle/gradle.properties
            echo $'\n'bintraykey=$bintraykey >> ${HOME}/.gradle/gradle.properties
            echo $'\n'artifactoryPassword=$artifactoryPassword >> ${HOME}/.gradle/gradle.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build
          command: ./gradlew assemble
      - run:
          name: Deploy Kaspresso
          command: ./gradlew :kaspresso:artifactoryPublish
      - store_artifacts:
          path: kaspresso/build/reports
          destination: reports/kaspresso
      - store_artifacts:
          path: uiautomator_dsl/build/reports
          destination: reports/uiautomator_dsl
      - store_test_results:
          path: kaspresso/build/test-results
workflows:
  version: 2
  main_workflow:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
                - snapshots

