#!/bin/bash
echo "Make ui damp and pull it"
pathToUiDump=$(adb shell uiautomator dump | grep -oE '/.*?xml')
adb pull "$pathToUiDump"
echo "Create page object"
java -jar page-object-code-gen.jar window_dump.xml "$1" "$2"
rm ./*.xml
